INSERT INTO AWS.DEPT (DEPTNO, DNAME, LOC, COMPLETED_BY) VALUES (10, 'ACCOUNTING', 'NEW YORK', 'ADMIN');
INSERT INTO AWS.DEPT (DEPTNO, DNAME, LOC, COMPLETED_BY) VALUES (20, 'RESEARCH', 'DALLAS', 'ADMIN');
INSERT INTO AWS.DEPT (DEPTNO, DNAME, LOC, COMPLETED_BY) VALUES (30, 'SALES', 'CHICAGO', null);
INSERT INTO AWS.DEPT (DEPTNO, DNAME, LOC, COMPLETED_BY) VALUES (40, 'OPERATIONS', 'BOSTON', 'ADMIN');
INSERT INTO AWS.DEPT (DEPTNO, DNAME, LOC, COMPLETED_BY) VALUES (70, 'sdfsdaf', 'sdafds', null);