INSERT INTO AWS.TB_CTT_DESCRIPTION (ID, TYPE, STATUS, NTT_NUMBER, DESCRIPTION, CHANGED_BY, WHEN) VALUES (14, null, 'ZAMKNIETe', 'aewrfqwer', null, 'SYSTEM_USEER', TO_DATE('2018-02-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO AWS.TB_CTT_DESCRIPTION (ID, TYPE, STATUS, NTT_NUMBER, DESCRIPTION, CHANGED_BY, WHEN) VALUES (12, 'sdfsdf', 'ZAMKNIETYD', 'NTT 16/05/001885+', 'duży opis powinien wyglądać lepiej 
Dlatego zrobię parę linii i zobaczhę co się stanie

Ciekawy jestem gdzie jest Antek i dlaczego go jeszcze nie ma u mnie

czy i kiedy wróci', 'ADMIN', TO_DATE('2018-02-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO AWS.TB_CTT_DESCRIPTION (ID, TYPE, STATUS, NTT_NUMBER, DESCRIPTION, CHANGED_BY, WHEN) VALUES (13, 'SDFDS', 'ZAMKNIĘTY', 'NTT 16/05/001618+', null, 'SYSTEM_USEER', TO_DATE('2018-02-11 10:39:29', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO AWS.TB_CTT_DESCRIPTION (ID, TYPE, STATUS, NTT_NUMBER, DESCRIPTION, CHANGED_BY, WHEN) VALUES (22, 'SDF', 'ASDFDSAF', 'SDFDSF', 'ASDFSDAF', 'SYSTEM_USEER', TO_DATE('2018-02-11 11:37:40', 'YYYY-MM-DD HH24:MI:SS'));